//
//  LocationWorker.swift
//  WeatherApp
//
//  Created by Cesar Brenes on 12/4/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocationStoreProtocol {
    func getCurrentLocation(completionHandler:@escaping (Result<Coordinates, WeatherAppError>) -> Void)
}

class LocationWorker {
    
    var store: LocationStoreProtocol
    
    init(store: LocationStoreProtocol) {
        self.store = store
    }
    
    func getCurrentLocation(completionHandler:@escaping (Result<Coordinates, WeatherAppError>) -> Void) {
        store.getCurrentLocation(completionHandler: completionHandler)
    }
    
}
