//
//  CurrentWeatherModels.swift
//  WeatherApp
//
//  Created by Cesar Brenes on 12/4/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CurrentWeather {
    
    enum UIInformation {
        struct Request {
            let needsANewLocationWorkerInstance: Bool // This is necessary to be able to inject a mock location worker from the unit tests 
        }
        struct Response {
            let result: Result<Weather, WeatherAppError>
        }
        struct ViewModel {
            struct Success {
                let name: String
                let iconURL: URL?
                let temperature: String
                let description: String
                let lowAndMaxTemperature: String
                let wind: String
                var isErrorViewHidden: Bool
                var isWeatherInformationViewHidden: Bool
            }
            struct ErrorFound {
                var title: String
                var message: String
                var isErrorViewHidden: Bool
                var isWeatherInformationViewHidden: Bool
            }
        }
    }
}
