//
//  CurrentWeatherRouter.swift
//  WeatherApp
//
//  Created by Cesar Brenes on 12/4/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CurrentWeatherRoutingLogic {
    
}

protocol CurrentWeatherDataPassing {
    var dataStore: CurrentWeatherDataStore? { get }
}

class CurrentWeatherRouter: NSObject, CurrentWeatherRoutingLogic, CurrentWeatherDataPassing {
    weak var viewController: CurrentWeatherViewController?
    var dataStore: CurrentWeatherDataStore?
}
